(function(e, a) { for(var i in a) e[i] = a[i]; }(exports, /******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, {
/******/ 				configurable: false,
/******/ 				enumerable: true,
/******/ 				get: getter
/******/ 			});
/******/ 		}
/******/ 	};
/******/
/******/ 	// define __esModule on exports
/******/ 	__webpack_require__.r = function(exports) {
/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = 0);
/******/ })
/************************************************************************/
/******/ ({

/***/ "./node_modules/@angular/router/router.ngfactory.js":
/*!**********************************************************!*\
  !*** ./node_modules/@angular/router/router.ngfactory.js ***!
  \**********************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i1 = __webpack_require__(/*! @angular/router */ "@angular/router");
var RouterModuleNgFactory = i0.ɵcmf(i1.RouterModule, [], function (_l) { return i0.ɵmod([i0.ɵmpd(512, i0.ComponentFactoryResolver, i0.ɵCodegenComponentFactoryResolver, [[8, [ɵEmptyOutletComponentNgFactory]], [3, i0.ComponentFactoryResolver], i0.NgModuleRef]), i0.ɵmpd(1073742336, i1.RouterModule, i1.RouterModule, [[2, i1.ɵangular_packages_router_router_a], [2, i1.Router]])]); });
exports.RouterModuleNgFactory = RouterModuleNgFactory;
var styles_ɵEmptyOutletComponent = [];
var RenderType_ɵEmptyOutletComponent = i0.ɵcrt({ encapsulation: 2, styles: styles_ɵEmptyOutletComponent, data: {} });
exports.RenderType_ɵEmptyOutletComponent = RenderType_ɵEmptyOutletComponent;
function View_ɵEmptyOutletComponent_0(_l) { return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, 16777216, null, null, 1, "router-outlet", [], null, null, null, null, null)), i0.ɵdid(1, 212992, null, 0, i1.RouterOutlet, [i1.ChildrenOutletContexts, i0.ViewContainerRef, i0.ComponentFactoryResolver, [8, null], i0.ChangeDetectorRef], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_ɵEmptyOutletComponent_0 = View_ɵEmptyOutletComponent_0;
function View_ɵEmptyOutletComponent_Host_0(_l) { return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, 0, null, null, 1, "ng-component", [], null, null, null, View_ɵEmptyOutletComponent_0, RenderType_ɵEmptyOutletComponent)), i0.ɵdid(1, 49152, null, 0, i1.ɵEmptyOutletComponent, [], null, null)], null, null); }
exports.View_ɵEmptyOutletComponent_Host_0 = View_ɵEmptyOutletComponent_Host_0;
var ɵEmptyOutletComponentNgFactory = i0.ɵccf("ng-component", i1.ɵEmptyOutletComponent, View_ɵEmptyOutletComponent_Host_0, {}, {}, []);
exports.ɵEmptyOutletComponentNgFactory = ɵEmptyOutletComponentNgFactory;


/***/ }),

/***/ "./src/app/app-routing.module.ts":
/*!***************************************!*\
  !*** ./src/app/app-routing.module.ts ***!
  \***************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var router_1 = __webpack_require__(/*! @angular/router */ "@angular/router");
var home_component_1 = __webpack_require__(/*! ./home/home.component */ "./src/app/home/home.component.ts");
var programming_component_1 = __webpack_require__(/*! ./programming/programming.component */ "./src/app/programming/programming.component.ts");
var music_component_1 = __webpack_require__(/*! ./music/music.component */ "./src/app/music/music.component.ts");
var lifting_component_1 = __webpack_require__(/*! ./lifting/lifting.component */ "./src/app/lifting/lifting.component.ts");
var pagenotfound_component_1 = __webpack_require__(/*! ./pagenotfound.component */ "./src/app/pagenotfound.component.ts");
var routes = [
    { path: '', redirectTo: '/home', pathMatch: 'full' },
    { path: 'home', component: home_component_1.HomeComponent },
    { path: 'programming', component: programming_component_1.ProgrammingComponent },
    { path: 'music', component: music_component_1.MusicComponent },
    { path: 'weightlifting', component: lifting_component_1.LiftingComponent },
    { path: '**', component: pagenotfound_component_1.PageNotFoundComponent }
];
var AppRoutingModule = /** @class */ (function () {
    function AppRoutingModule() {
    }
    return AppRoutingModule;
}());
exports.AppRoutingModule = AppRoutingModule;


/***/ }),

/***/ "./src/app/app.component.ngfactory.js":
/*!********************************************!*\
  !*** ./src/app/app.component.ngfactory.js ***!
  \********************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i1 = __webpack_require__(/*! @angular/router */ "@angular/router");
var i2 = __webpack_require__(/*! @angular/common */ "@angular/common");
var i3 = __webpack_require__(/*! ./app.component */ "./src/app/app.component.ts");
var styles_AppComponent = [];
var RenderType_AppComponent = i0.ɵcrt({ encapsulation: 2, styles: styles_AppComponent, data: {} });
exports.RenderType_AppComponent = RenderType_AppComponent;
function View_AppComponent_0(_l) { return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, 0, null, null, 28, "nav", [], null, null, null, null, null)), (_l()(), i0.ɵeld(1, 0, null, null, 6, "li", [], null, null, null, null, null)), (_l()(), i0.ɵeld(2, 0, null, null, 5, "a", [["routerLink", "/home"], ["routerLinkActive", "active"]], [[1, "target", 0], [8, "href", 4]], [[null, "click"]], function (_v, en, $event) { var ad = true; if (("click" === en)) {
        var pd_0 = (i0.ɵnov(_v, 3).onClick($event.button, $event.ctrlKey, $event.metaKey, $event.shiftKey) !== false);
        ad = (pd_0 && ad);
    } return ad; }, null, null)), i0.ɵdid(3, 671744, [[2, 4]], 0, i1.RouterLinkWithHref, [i1.Router, i1.ActivatedRoute, i2.LocationStrategy], { routerLink: [0, "routerLink"] }, null), i0.ɵdid(4, 1720320, null, 2, i1.RouterLinkActive, [i1.Router, i0.ElementRef, i0.Renderer2, i0.ChangeDetectorRef], { routerLinkActive: [0, "routerLinkActive"] }, null), i0.ɵqud(603979776, 1, { links: 1 }), i0.ɵqud(603979776, 2, { linksWithHrefs: 1 }), (_l()(), i0.ɵted(-1, null, ["Home"])), (_l()(), i0.ɵeld(8, 0, null, null, 6, "li", [], null, null, null, null, null)), (_l()(), i0.ɵeld(9, 0, null, null, 5, "a", [["routerLink", "/programming"], ["routerLinkActive", "active"]], [[1, "target", 0], [8, "href", 4]], [[null, "click"]], function (_v, en, $event) { var ad = true; if (("click" === en)) {
        var pd_0 = (i0.ɵnov(_v, 10).onClick($event.button, $event.ctrlKey, $event.metaKey, $event.shiftKey) !== false);
        ad = (pd_0 && ad);
    } return ad; }, null, null)), i0.ɵdid(10, 671744, [[4, 4]], 0, i1.RouterLinkWithHref, [i1.Router, i1.ActivatedRoute, i2.LocationStrategy], { routerLink: [0, "routerLink"] }, null), i0.ɵdid(11, 1720320, null, 2, i1.RouterLinkActive, [i1.Router, i0.ElementRef, i0.Renderer2, i0.ChangeDetectorRef], { routerLinkActive: [0, "routerLinkActive"] }, null), i0.ɵqud(603979776, 3, { links: 1 }), i0.ɵqud(603979776, 4, { linksWithHrefs: 1 }), (_l()(), i0.ɵted(-1, null, ["Programming"])), (_l()(), i0.ɵeld(15, 0, null, null, 6, "li", [], null, null, null, null, null)), (_l()(), i0.ɵeld(16, 0, null, null, 5, "a", [["routerLink", "/music"], ["routerLinkActive", "active"]], [[1, "target", 0], [8, "href", 4]], [[null, "click"]], function (_v, en, $event) { var ad = true; if (("click" === en)) {
        var pd_0 = (i0.ɵnov(_v, 17).onClick($event.button, $event.ctrlKey, $event.metaKey, $event.shiftKey) !== false);
        ad = (pd_0 && ad);
    } return ad; }, null, null)), i0.ɵdid(17, 671744, [[6, 4]], 0, i1.RouterLinkWithHref, [i1.Router, i1.ActivatedRoute, i2.LocationStrategy], { routerLink: [0, "routerLink"] }, null), i0.ɵdid(18, 1720320, null, 2, i1.RouterLinkActive, [i1.Router, i0.ElementRef, i0.Renderer2, i0.ChangeDetectorRef], { routerLinkActive: [0, "routerLinkActive"] }, null), i0.ɵqud(603979776, 5, { links: 1 }), i0.ɵqud(603979776, 6, { linksWithHrefs: 1 }), (_l()(), i0.ɵted(-1, null, ["Music"])), (_l()(), i0.ɵeld(22, 0, null, null, 6, "li", [], null, null, null, null, null)), (_l()(), i0.ɵeld(23, 0, null, null, 5, "a", [["routerLink", "/weightlifting"], ["routerLinkActive", "active"]], [[1, "target", 0], [8, "href", 4]], [[null, "click"]], function (_v, en, $event) { var ad = true; if (("click" === en)) {
        var pd_0 = (i0.ɵnov(_v, 24).onClick($event.button, $event.ctrlKey, $event.metaKey, $event.shiftKey) !== false);
        ad = (pd_0 && ad);
    } return ad; }, null, null)), i0.ɵdid(24, 671744, [[8, 4]], 0, i1.RouterLinkWithHref, [i1.Router, i1.ActivatedRoute, i2.LocationStrategy], { routerLink: [0, "routerLink"] }, null), i0.ɵdid(25, 1720320, null, 2, i1.RouterLinkActive, [i1.Router, i0.ElementRef, i0.Renderer2, i0.ChangeDetectorRef], { routerLinkActive: [0, "routerLinkActive"] }, null), i0.ɵqud(603979776, 7, { links: 1 }), i0.ɵqud(603979776, 8, { linksWithHrefs: 1 }), (_l()(), i0.ɵted(-1, null, ["Weightlifting"])), (_l()(), i0.ɵeld(29, 0, null, null, 1, "h1", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, ["Egill Antonsson"])), (_l()(), i0.ɵeld(31, 16777216, null, null, 1, "router-outlet", [], null, null, null, null, null)), i0.ɵdid(32, 212992, null, 0, i1.RouterOutlet, [i1.ChildrenOutletContexts, i0.ViewContainerRef, i0.ComponentFactoryResolver, [8, null], i0.ChangeDetectorRef], null, null)], function (_ck, _v) { var currVal_2 = "/home"; _ck(_v, 3, 0, currVal_2); var currVal_3 = "active"; _ck(_v, 4, 0, currVal_3); var currVal_6 = "/programming"; _ck(_v, 10, 0, currVal_6); var currVal_7 = "active"; _ck(_v, 11, 0, currVal_7); var currVal_10 = "/music"; _ck(_v, 17, 0, currVal_10); var currVal_11 = "active"; _ck(_v, 18, 0, currVal_11); var currVal_14 = "/weightlifting"; _ck(_v, 24, 0, currVal_14); var currVal_15 = "active"; _ck(_v, 25, 0, currVal_15); _ck(_v, 32, 0); }, function (_ck, _v) { var currVal_0 = i0.ɵnov(_v, 3).target; var currVal_1 = i0.ɵnov(_v, 3).href; _ck(_v, 2, 0, currVal_0, currVal_1); var currVal_4 = i0.ɵnov(_v, 10).target; var currVal_5 = i0.ɵnov(_v, 10).href; _ck(_v, 9, 0, currVal_4, currVal_5); var currVal_8 = i0.ɵnov(_v, 17).target; var currVal_9 = i0.ɵnov(_v, 17).href; _ck(_v, 16, 0, currVal_8, currVal_9); var currVal_12 = i0.ɵnov(_v, 24).target; var currVal_13 = i0.ɵnov(_v, 24).href; _ck(_v, 23, 0, currVal_12, currVal_13); }); }
exports.View_AppComponent_0 = View_AppComponent_0;
function View_AppComponent_Host_0(_l) { return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, 0, null, null, 1, "app-root", [], null, null, null, View_AppComponent_0, RenderType_AppComponent)), i0.ɵdid(1, 49152, null, 0, i3.AppComponent, [], null, null)], null, null); }
exports.View_AppComponent_Host_0 = View_AppComponent_Host_0;
var AppComponentNgFactory = i0.ɵccf("app-root", i3.AppComponent, View_AppComponent_Host_0, {}, {}, []);
exports.AppComponentNgFactory = AppComponentNgFactory;


/***/ }),

/***/ "./src/app/app.component.ts":
/*!**********************************!*\
  !*** ./src/app/app.component.ts ***!
  \**********************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var AppComponent = /** @class */ (function () {
    function AppComponent() {
    }
    return AppComponent;
}());
exports.AppComponent = AppComponent;


/***/ }),

/***/ "./src/app/app.module.ts":
/*!*******************************!*\
  !*** ./src/app/app.module.ts ***!
  \*******************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var common_1 = __webpack_require__(/*! @angular/common */ "@angular/common");
var AppModule = /** @class */ (function () {
    function AppModule(platformId, appId) {
        this.platformId = platformId;
        this.appId = appId;
        var platform = common_1.isPlatformBrowser(platformId) ?
            'in the browser' : 'on the server';
        console.log("Running " + platform + " with appId=" + appId);
    }
    return AppModule;
}());
exports.AppModule = AppModule;


/***/ }),

/***/ "./src/app/app.server.module.ngfactory.js":
/*!************************************************!*\
  !*** ./src/app/app.server.module.ngfactory.js ***!
  \************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i1 = __webpack_require__(/*! ./app.server.module */ "./src/app/app.server.module.ts");
var i2 = __webpack_require__(/*! ./app.component */ "./src/app/app.component.ts");
var i3 = __webpack_require__(/*! ../../node_modules/@angular/router/router.ngfactory */ "./node_modules/@angular/router/router.ngfactory.js");
var i4 = __webpack_require__(/*! ./home/home.component.ngfactory */ "./src/app/home/home.component.ngfactory.js");
var i5 = __webpack_require__(/*! ./programming/programming.component.ngfactory */ "./src/app/programming/programming.component.ngfactory.js");
var i6 = __webpack_require__(/*! ./music/music.component.ngfactory */ "./src/app/music/music.component.ngfactory.js");
var i7 = __webpack_require__(/*! ./lifting/lifting.component.ngfactory */ "./src/app/lifting/lifting.component.ngfactory.js");
var i8 = __webpack_require__(/*! ./pagenotfound.component.ngfactory */ "./src/app/pagenotfound.component.ngfactory.js");
var i9 = __webpack_require__(/*! ./app.component.ngfactory */ "./src/app/app.component.ngfactory.js");
var i10 = __webpack_require__(/*! @angular/common */ "@angular/common");
var i11 = __webpack_require__(/*! @angular/platform-browser */ "@angular/platform-browser");
var i12 = __webpack_require__(/*! @angular/platform-server */ "@angular/platform-server");
var i13 = __webpack_require__(/*! @angular/animations/browser */ "@angular/animations/browser");
var i14 = __webpack_require__(/*! @angular/platform-browser/animations */ "@angular/platform-browser/animations");
var i15 = __webpack_require__(/*! @angular/router */ "@angular/router");
var i16 = __webpack_require__(/*! @angular/common/http */ "@angular/common/http");
var i17 = __webpack_require__(/*! @angular/http */ "@angular/http");
var i18 = __webpack_require__(/*! @angular/animations */ "@angular/animations");
var i19 = __webpack_require__(/*! @nguniversal/module-map-ngfactory-loader */ "@nguniversal/module-map-ngfactory-loader");
var i20 = __webpack_require__(/*! ./home/home.component */ "./src/app/home/home.component.ts");
var i21 = __webpack_require__(/*! ./programming/programming.component */ "./src/app/programming/programming.component.ts");
var i22 = __webpack_require__(/*! ./music/music.component */ "./src/app/music/music.component.ts");
var i23 = __webpack_require__(/*! ./lifting/lifting.component */ "./src/app/lifting/lifting.component.ts");
var i24 = __webpack_require__(/*! ./pagenotfound.component */ "./src/app/pagenotfound.component.ts");
var i25 = __webpack_require__(/*! ./app-routing.module */ "./src/app/app-routing.module.ts");
var i26 = __webpack_require__(/*! ./app.module */ "./src/app/app.module.ts");
var AppServerModuleNgFactory = i0.ɵcmf(i1.AppServerModule, [i2.AppComponent], function (_l) { return i0.ɵmod([i0.ɵmpd(512, i0.ComponentFactoryResolver, i0.ɵCodegenComponentFactoryResolver, [[8, [i3.ɵEmptyOutletComponentNgFactory, i4.HomeComponentNgFactory, i5.ProgrammingComponentNgFactory, i6.MusicComponentNgFactory, i7.LiftingComponentNgFactory, i8.PageNotFoundComponentNgFactory, i9.AppComponentNgFactory]], [3, i0.ComponentFactoryResolver], i0.NgModuleRef]), i0.ɵmpd(5120, i0.LOCALE_ID, i0.ɵangular_packages_core_core_k, [[3, i0.LOCALE_ID]]), i0.ɵmpd(4608, i10.NgLocalization, i10.NgLocaleLocalization, [i0.LOCALE_ID, [2, i10.ɵangular_packages_common_common_a]]), i0.ɵmpd(5120, i0.IterableDiffers, i0.ɵangular_packages_core_core_i, []), i0.ɵmpd(5120, i0.KeyValueDiffers, i0.ɵangular_packages_core_core_j, []), i0.ɵmpd(4608, i11.DomSanitizer, i11.ɵDomSanitizerImpl, [i10.DOCUMENT]), i0.ɵmpd(6144, i0.Sanitizer, null, [i11.DomSanitizer]), i0.ɵmpd(4608, i11.HAMMER_GESTURE_CONFIG, i11.HammerGestureConfig, []), i0.ɵmpd(5120, i11.EVENT_MANAGER_PLUGINS, function (p0_0, p0_1, p0_2, p1_0, p2_0, p2_1, p2_2, p2_3, p3_0) { return [new i11.ɵDomEventsPlugin(p0_0, p0_1, p0_2), new i11.ɵKeyEventsPlugin(p1_0), new i11.ɵHammerGesturesPlugin(p2_0, p2_1, p2_2, p2_3), new i12.ɵangular_packages_platform_server_platform_server_d(p3_0)]; }, [i10.DOCUMENT, i0.NgZone, i0.PLATFORM_ID, i10.DOCUMENT, i10.DOCUMENT, i11.HAMMER_GESTURE_CONFIG, i0.ɵConsole, [2, i11.HAMMER_LOADER], i11.DOCUMENT]), i0.ɵmpd(4608, i11.EventManager, i11.EventManager, [i11.EVENT_MANAGER_PLUGINS, i0.NgZone]), i0.ɵmpd(135680, i11.ɵDomSharedStylesHost, i11.ɵDomSharedStylesHost, [i10.DOCUMENT]), i0.ɵmpd(4608, i11.ɵDomRendererFactory2, i11.ɵDomRendererFactory2, [i11.EventManager, i11.ɵDomSharedStylesHost]), i0.ɵmpd(4608, i12.ɵangular_packages_platform_server_platform_server_c, i12.ɵangular_packages_platform_server_platform_server_c, [i11.DOCUMENT, [2, i11.ɵTRANSITION_ID]]), i0.ɵmpd(6144, i11.ɵSharedStylesHost, null, [i12.ɵangular_packages_platform_server_platform_server_c]), i0.ɵmpd(4608, i12.ɵServerRendererFactory2, i12.ɵServerRendererFactory2, [i11.EventManager, i0.NgZone, i11.DOCUMENT, i11.ɵSharedStylesHost]), i0.ɵmpd(4608, i13.AnimationDriver, i13.ɵNoopAnimationDriver, []), i0.ɵmpd(5120, i13.ɵAnimationStyleNormalizer, i14.ɵangular_packages_platform_browser_animations_animations_c, []), i0.ɵmpd(4608, i13.ɵAnimationEngine, i14.ɵangular_packages_platform_browser_animations_animations_a, [i10.DOCUMENT, i13.AnimationDriver, i13.ɵAnimationStyleNormalizer]), i0.ɵmpd(5120, i0.RendererFactory2, i12.ɵangular_packages_platform_server_platform_server_a, [i12.ɵServerRendererFactory2, i13.ɵAnimationEngine, i0.NgZone]), i0.ɵmpd(4352, i0.Testability, null, []), i0.ɵmpd(5120, i15.ActivatedRoute, i15.ɵangular_packages_router_router_g, [i15.Router]), i0.ɵmpd(4608, i15.NoPreloading, i15.NoPreloading, []), i0.ɵmpd(6144, i15.PreloadingStrategy, null, [i15.NoPreloading]), i0.ɵmpd(135680, i15.RouterPreloader, i15.RouterPreloader, [i15.Router, i0.NgModuleFactoryLoader, i0.Compiler, i0.Injector, i15.PreloadingStrategy]), i0.ɵmpd(4608, i15.PreloadAllModules, i15.PreloadAllModules, []), i0.ɵmpd(4608, i10.ViewportScroller, i10.ɵNullViewportScroller, []), i0.ɵmpd(5120, i15.ɵangular_packages_router_router_n, i15.ɵangular_packages_router_router_c, [i15.Router, i10.ViewportScroller, i15.ROUTER_CONFIGURATION]), i0.ɵmpd(5120, i15.ROUTER_INITIALIZER, i15.ɵangular_packages_router_router_j, [i15.ɵangular_packages_router_router_h]), i0.ɵmpd(5120, i0.APP_BOOTSTRAP_LISTENER, function (p0_0) { return [p0_0]; }, [i15.ROUTER_INITIALIZER]), i0.ɵmpd(4608, i16.HttpXsrfTokenExtractor, i16.ɵangular_packages_common_http_http_g, [i10.DOCUMENT, i0.PLATFORM_ID, i16.ɵangular_packages_common_http_http_e]), i0.ɵmpd(4608, i16.ɵangular_packages_common_http_http_h, i16.ɵangular_packages_common_http_http_h, [i16.HttpXsrfTokenExtractor, i16.ɵangular_packages_common_http_http_f]), i0.ɵmpd(5120, i16.HTTP_INTERCEPTORS, function (p0_0) { return [p0_0]; }, [i16.ɵangular_packages_common_http_http_h]), i0.ɵmpd(4608, i16.XhrFactory, i12.ɵangular_packages_platform_server_platform_server_e, []), i0.ɵmpd(4608, i16.HttpXhrBackend, i16.HttpXhrBackend, [i16.XhrFactory]), i0.ɵmpd(6144, i16.HttpBackend, null, [i16.HttpXhrBackend]), i0.ɵmpd(5120, i16.HttpHandler, i12.ɵangular_packages_platform_server_platform_server_h, [i16.HttpBackend, i0.Injector]), i0.ɵmpd(4608, i16.HttpClient, i16.HttpClient, [i16.HttpHandler]), i0.ɵmpd(4608, i16.ɵangular_packages_common_http_http_d, i16.ɵangular_packages_common_http_http_d, []), i0.ɵmpd(4608, i17.BrowserXhr, i12.ɵangular_packages_platform_server_platform_server_e, []), i0.ɵmpd(4608, i17.ResponseOptions, i17.BaseResponseOptions, []), i0.ɵmpd(4608, i17.XSRFStrategy, i12.ɵangular_packages_platform_server_platform_server_f, []), i0.ɵmpd(4608, i17.XHRBackend, i17.XHRBackend, [i17.BrowserXhr, i17.ResponseOptions, i17.XSRFStrategy]), i0.ɵmpd(4608, i17.RequestOptions, i17.BaseRequestOptions, []), i0.ɵmpd(5120, i17.Http, i12.ɵangular_packages_platform_server_platform_server_g, [i17.XHRBackend, i17.RequestOptions]), i0.ɵmpd(4608, i18.AnimationBuilder, i14.ɵBrowserAnimationBuilder, [i0.RendererFactory2, i11.DOCUMENT]), i0.ɵmpd(1073742336, i10.CommonModule, i10.CommonModule, []), i0.ɵmpd(1024, i0.ErrorHandler, i11.ɵangular_packages_platform_browser_platform_browser_a, []), i0.ɵmpd(1024, i0.NgProbeToken, function () { return [i15.ɵangular_packages_router_router_b()]; }, []), i0.ɵmpd(512, i15.ɵangular_packages_router_router_h, i15.ɵangular_packages_router_router_h, [i0.Injector]), i0.ɵmpd(256, i0.APP_ID, "egill-website", []), i0.ɵmpd(2048, i11.ɵTRANSITION_ID, null, [i0.APP_ID]), i0.ɵmpd(1024, i0.APP_INITIALIZER, function (p0_0, p1_0, p2_0, p2_1, p2_2) { return [i11.ɵangular_packages_platform_browser_platform_browser_j(p0_0), i15.ɵangular_packages_router_router_i(p1_0), i11.ɵangular_packages_platform_browser_platform_browser_h(p2_0, p2_1, p2_2)]; }, [[2, i0.NgProbeToken], i15.ɵangular_packages_router_router_h, i11.ɵTRANSITION_ID, i10.DOCUMENT, i0.Injector]), i0.ɵmpd(512, i0.ApplicationInitStatus, i0.ApplicationInitStatus, [[2, i0.APP_INITIALIZER]]), i0.ɵmpd(131584, i0.ApplicationRef, i0.ApplicationRef, [i0.NgZone, i0.ɵConsole, i0.Injector, i0.ErrorHandler, i0.ComponentFactoryResolver, i0.ApplicationInitStatus]), i0.ɵmpd(1073742336, i0.ApplicationModule, i0.ApplicationModule, [i0.ApplicationRef]), i0.ɵmpd(1073742336, i11.BrowserModule, i11.BrowserModule, [[3, i11.BrowserModule]]), i0.ɵmpd(1024, i15.ɵangular_packages_router_router_a, i15.ɵangular_packages_router_router_e, [[3, i15.Router]]), i0.ɵmpd(512, i15.UrlSerializer, i15.DefaultUrlSerializer, []), i0.ɵmpd(512, i15.ChildrenOutletContexts, i15.ChildrenOutletContexts, []), i0.ɵmpd(256, i15.ROUTER_CONFIGURATION, { enableTracing: false }, []), i0.ɵmpd(1024, i10.LocationStrategy, i15.ɵangular_packages_router_router_d, [i10.PlatformLocation, [2, i10.APP_BASE_HREF], i15.ROUTER_CONFIGURATION]), i0.ɵmpd(512, i10.Location, i10.Location, [i10.LocationStrategy]), i0.ɵmpd(512, i0.Compiler, i0.Compiler, []), i0.ɵmpd(512, i0.NgModuleFactoryLoader, i19.ModuleMapNgFactoryLoader, [i0.Compiler, i19.MODULE_MAP]), i0.ɵmpd(1024, i15.ROUTES, function () { return [[{ path: "", redirectTo: "/home", pathMatch: "full" }, { path: "home", component: i20.HomeComponent }, { path: "programming", component: i21.ProgrammingComponent }, { path: "music", component: i22.MusicComponent }, { path: "weightlifting", component: i23.LiftingComponent }, { path: "**", component: i24.PageNotFoundComponent }]]; }, []), i0.ɵmpd(1024, i15.Router, i15.ɵangular_packages_router_router_f, [i0.ApplicationRef, i15.UrlSerializer, i15.ChildrenOutletContexts, i10.Location, i0.Injector, i0.NgModuleFactoryLoader, i0.Compiler, i15.ROUTES, i15.ROUTER_CONFIGURATION, [2, i15.UrlHandlingStrategy], [2, i15.RouteReuseStrategy]]), i0.ɵmpd(1073742336, i15.RouterModule, i15.RouterModule, [[2, i15.ɵangular_packages_router_router_a], [2, i15.Router]]), i0.ɵmpd(1073742336, i25.AppRoutingModule, i25.AppRoutingModule, []), i0.ɵmpd(1073742336, i16.HttpClientXsrfModule, i16.HttpClientXsrfModule, []), i0.ɵmpd(1073742336, i16.HttpClientModule, i16.HttpClientModule, []), i0.ɵmpd(1073742336, i26.AppModule, i26.AppModule, [i0.PLATFORM_ID, i0.APP_ID]), i0.ɵmpd(1073742336, i17.HttpModule, i17.HttpModule, []), i0.ɵmpd(1073742336, i14.NoopAnimationsModule, i14.NoopAnimationsModule, []), i0.ɵmpd(1073742336, i12.ServerModule, i12.ServerModule, []), i0.ɵmpd(1073742336, i19.ModuleMapLoaderModule, i19.ModuleMapLoaderModule, []), i0.ɵmpd(1073742336, i1.AppServerModule, i1.AppServerModule, []), i0.ɵmpd(256, i0.ɵAPP_ROOT, true, []), i0.ɵmpd(256, i16.ɵangular_packages_common_http_http_e, "XSRF-TOKEN", []), i0.ɵmpd(256, i16.ɵangular_packages_common_http_http_f, "X-XSRF-TOKEN", []), i0.ɵmpd(256, i14.ANIMATION_MODULE_TYPE, "NoopAnimations", [])]); });
exports.AppServerModuleNgFactory = AppServerModuleNgFactory;


/***/ }),

/***/ "./src/app/app.server.module.ts":
/*!**************************************!*\
  !*** ./src/app/app.server.module.ts ***!
  \**************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var AppServerModule = /** @class */ (function () {
    function AppServerModule() {
    }
    return AppServerModule;
}());
exports.AppServerModule = AppServerModule;


/***/ }),

/***/ "./src/app/home/home.component.ngfactory.js":
/*!**************************************************!*\
  !*** ./src/app/home/home.component.ngfactory.js ***!
  \**************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i1 = __webpack_require__(/*! ./home.component */ "./src/app/home/home.component.ts");
var styles_HomeComponent = [];
var RenderType_HomeComponent = i0.ɵcrt({ encapsulation: 2, styles: styles_HomeComponent, data: {} });
exports.RenderType_HomeComponent = RenderType_HomeComponent;
function View_HomeComponent_0(_l) { return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, 0, null, null, 1, "h2", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, ["Software developer, music artist, weightlifter, earthling"])), (_l()(), i0.ɵeld(2, 0, null, null, 44, "div", [["class", "left"]], null, null, null, null, null)), (_l()(), i0.ɵeld(3, 0, null, null, 8, "p", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, [" Welcome to my website."])), (_l()(), i0.ɵeld(5, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, [" I want to share my creations and progress on my passions: Programming, Music and Weightlifting."])), (_l()(), i0.ɵeld(7, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, [" I'm a Senior Developer at "])), (_l()(), i0.ɵeld(9, 0, null, null, 1, "a", [["href", "https://king.com"]], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, ["King"])), (_l()(), i0.ɵted(-1, null, [" where I develop shared tech for the mobile games.\n"])), (_l()(), i0.ɵeld(12, 0, null, null, 1, "h2", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, ["Background & Family"])), (_l()(), i0.ɵeld(14, 0, null, null, 6, "p", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, [" I was born in 1982 and raised in Reykjavik, Iceland."])), (_l()(), i0.ɵeld(16, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, [" Since 2014 I live in Stockholm, Sweden with my wonderful wife Jantra Phosri and daughter Soff\u00EDa R\u00F3s Egilsd\u00F3ttir."])), (_l()(), i0.ɵeld(18, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, [" I'm a proud bonus/step dad of Andri Reyr Ragnarsson who lives in Norway."])), (_l()(), i0.ɵeld(20, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i0.ɵeld(21, 0, null, null, 6, "div", [["class", "right"]], null, null, null, null, null)), (_l()(), i0.ɵeld(22, 0, null, null, 5, "figure", [], null, null, null, null, null)), (_l()(), i0.ɵeld(23, 0, null, null, 0, "img", [["alt", "The family: Egill Antonsson, Soff\u00EDa R\u00F3s Egilsd\u00F3ttir, Jantra Phosri & Andri Reyr Ragnarsson"], ["class", "image"], ["src", "../assets/family.jpg"], ["title", "The family: Egill Antonsson, Soff\u00EDa R\u00F3s Egilsd\u00F3ttir, Jantra Phosri & Andri Reyr Ragnarsson"]], null, null, null, null, null)), (_l()(), i0.ɵeld(24, 0, null, null, 3, "figcaption", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, [" The family, from left to right:"])), (_l()(), i0.ɵeld(26, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, [" Egill Antonsson, Soff\u00EDa R\u00F3s Egilsd\u00F3ttir, Jantra Phosri & Andri Reyr Ragnarsson "])), (_l()(), i0.ɵeld(28, 0, null, null, 18, "div", [["class", "left"]], null, null, null, null, null)), (_l()(), i0.ɵeld(29, 0, null, null, 17, "p", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, [" I'm son of Anton Angant\u00FDsson (that's what my last name literally means) and Halla Soff\u00EDa J\u00F3nasd\u00F3ttir and they live in Iceland."])), (_l()(), i0.ɵeld(31, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, [" I have a brother J\u00F3nas B. Antonsson and he also lives in Stockholm and he's unpublishing games like a Boss at "])), (_l()(), i0.ɵeld(33, 0, null, null, 1, "a", [["href", "https://rawfury.com"]], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, ["Raw Fury"])), (_l()(), i0.ɵted(-1, null, ["."])), (_l()(), i0.ɵeld(36, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, [" Our two older brothers J\u00F3nas Bj\u00F6rgvin Antonsson and Egill Antonsson passed away before I was born."])), (_l()(), i0.ɵeld(38, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, [" They played music and painted pictures and according to family and friends were brilliant boys."])), (_l()(), i0.ɵeld(40, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, [" I've digitalized their "])), (_l()(), i0.ɵeld(42, 0, null, null, 1, "a", [["href", "/music"]], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, ["music"])), (_l()(), i0.ɵted(-1, null, [" that they recorded on a cassette in the early 1970s"])), (_l()(), i0.ɵeld(45, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, [" (these songs have a picture of the cassette in the SoundCloud player following the link).\n"]))], null, null); }
exports.View_HomeComponent_0 = View_HomeComponent_0;
function View_HomeComponent_Host_0(_l) { return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, 0, null, null, 1, "app-home", [], null, null, null, View_HomeComponent_0, RenderType_HomeComponent)), i0.ɵdid(1, 49152, null, 0, i1.HomeComponent, [], null, null)], null, null); }
exports.View_HomeComponent_Host_0 = View_HomeComponent_Host_0;
var HomeComponentNgFactory = i0.ɵccf("app-home", i1.HomeComponent, View_HomeComponent_Host_0, {}, {}, []);
exports.HomeComponentNgFactory = HomeComponentNgFactory;


/***/ }),

/***/ "./src/app/home/home.component.ts":
/*!****************************************!*\
  !*** ./src/app/home/home.component.ts ***!
  \****************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var HomeComponent = /** @class */ (function () {
    function HomeComponent() {
    }
    return HomeComponent;
}());
exports.HomeComponent = HomeComponent;


/***/ }),

/***/ "./src/app/lifting/lifting.component.css.shim.ngstyle.js":
/*!***************************************************************!*\
  !*** ./src/app/lifting/lifting.component.css.shim.ngstyle.js ***!
  \***************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [".weightTable[_ngcontent-%COMP%] {\r\n\tborder: 8px groove #ccc;\r\n}\r\n\r\ntable[_ngcontent-%COMP%]   td[_ngcontent-%COMP%] {\r\n\tborder: 4px double #ccc;\r\n\tpadding: 0.5em;\r\n}\r\n\r\ntable[_ngcontent-%COMP%]   td.center[_ngcontent-%COMP%] {\r\n\ttext-align: center;\r\n}\r\n\r\ntable[_ngcontent-%COMP%]   th[_ngcontent-%COMP%] {\r\n\tborder: 4px double #ccc;\r\n\tpadding: 0.5em;\r\n}"];
exports.styles = styles;


/***/ }),

/***/ "./src/app/lifting/lifting.component.ngfactory.js":
/*!********************************************************!*\
  !*** ./src/app/lifting/lifting.component.ngfactory.js ***!
  \********************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! ./lifting.component.css.shim.ngstyle */ "./src/app/lifting/lifting.component.css.shim.ngstyle.js");
var i1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i2 = __webpack_require__(/*! @angular/common */ "@angular/common");
var i3 = __webpack_require__(/*! ../pipes/mynumber.pipe */ "./src/app/pipes/mynumber.pipe.ts");
var i4 = __webpack_require__(/*! ./lifting.component */ "./src/app/lifting/lifting.component.ts");
var styles_LiftingComponent = [i0.styles];
var RenderType_LiftingComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_LiftingComponent, data: {} });
exports.RenderType_LiftingComponent = RenderType_LiftingComponent;
function View_LiftingComponent_1(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 5, "li", [], null, null, null, null, null)), (_l()(), i1.ɵted(1, null, [" ", "x "])), (_l()(), i1.ɵeld(2, 0, null, null, 1, "a", [], [[8, "href", 4]], null, null, null, null)), (_l()(), i1.ɵted(3, null, ["", ""])), (_l()(), i1.ɵted(4, null, [" (", " kg", ") "])), i1.ɵppd(5, 1)], null, function (_ck, _v) { var currVal_0 = _v.context.$implicit.count; _ck(_v, 1, 0, currVal_0); var currVal_1 = i1.ɵinlineInterpolate(1, "", _v.context.$implicit.creature.url, ""); _ck(_v, 2, 0, currVal_1); var currVal_2 = _v.context.$implicit.creature.name; _ck(_v, 3, 0, currVal_2); var currVal_3 = i1.ɵunv(_v, 4, 0, _ck(_v, 5, 0, i1.ɵnov(_v.parent, 1), _v.context.$implicit.creature.kg)); var currVal_4 = ((_v.context.$implicit.count > 1) ? " each" : ""); _ck(_v, 4, 0, currVal_3, currVal_4); }); }
function View_LiftingComponent_0(_l) { return i1.ɵvid(0, [i1.ɵpid(0, i2.DatePipe, [i1.LOCALE_ID]), i1.ɵpid(0, i3.MyNumberPipe, []), (_l()(), i1.ɵeld(2, 0, null, null, 34, "div", [], null, null, null, null, null)), (_l()(), i1.ɵeld(3, 0, null, null, 1, "h2", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Progressing on my path to lift the Platinum Dragon!"])), (_l()(), i1.ɵeld(5, 0, null, null, 3, "p", [], null, null, null, null, null)), (_l()(), i1.ɵted(6, null, ["\nDuring the period ", " - ", ":\n"])), i1.ɵppd(7, 2), i1.ɵppd(8, 2), (_l()(), i1.ɵeld(9, 0, null, null, 14, "table", [["class", "weightTable"]], null, null, null, null, null)), (_l()(), i1.ɵeld(10, 0, null, null, 13, "tbody", [], null, null, null, null, null)), (_l()(), i1.ɵeld(11, 0, null, null, 4, "tr", [], null, null, null, null, null)), (_l()(), i1.ɵeld(12, 0, null, null, 1, "th", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Tons lifted"])), (_l()(), i1.ɵeld(14, 0, null, null, 1, "th", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Creatures lifted"])), (_l()(), i1.ɵeld(16, 0, null, null, 7, "tr", [], null, null, null, null, null)), (_l()(), i1.ɵeld(17, 0, null, null, 2, "td", [["class", "center"]], null, null, null, null, null)), (_l()(), i1.ɵted(18, null, ["", ""])), i1.ɵppd(19, 4), (_l()(), i1.ɵeld(20, 0, null, null, 3, "td", [], null, null, null, null, null)), (_l()(), i1.ɵeld(21, 0, null, null, 2, "ul", [], null, null, null, null, null)), (_l()(), i1.ɵand(16777216, null, null, 1, null, View_LiftingComponent_1)), i1.ɵdid(23, 278528, null, 0, i2.NgForOf, [i1.ViewContainerRef, i1.TemplateRef, i1.IterableDiffers], { ngForOf: [0, "ngForOf"] }, null), (_l()(), i1.ɵeld(24, 0, null, null, 12, "p", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" No animal was hurt during the lifting (maybe their pride a little bit)."])), (_l()(), i1.ɵeld(26, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" The sources for the creature weight list:"])), (_l()(), i1.ɵeld(28, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i1.ɵeld(29, 0, null, null, 1, "a", [["href", "http://forgottenrealms.wikia.com/wiki/Metallic_dragon"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Metallic dragons of the Forgotten Realms"])), (_l()(), i1.ɵeld(31, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i1.ɵeld(32, 0, null, null, 1, "a", [["href", "https://en.wikipedia.org/wiki/Dinosaur_size"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Dinosaur size"])), (_l()(), i1.ɵeld(34, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i1.ɵeld(35, 0, null, null, 1, "a", [["href", "https://thewebsiteofeverything.com/animals/mammals/adult-weight.html"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Adult mammals ordered by their weight"])), (_l()(), i1.ɵeld(37, 0, null, null, 4, "div", [], null, null, null, null, null)), (_l()(), i1.ɵeld(38, 0, null, null, 3, "figure", [], null, null, null, null, null)), (_l()(), i1.ɵeld(39, 0, null, null, 0, "img", [["alt", "Egill Antonsson dealing with the the dragon's breath by wearing shades"], ["class", "image"], ["src", "../assets/Egill_Antonsson.jpg"], ["title", "Egill Antonsson dealing with the the dragon's breath"]], null, null, null, null, null)), (_l()(), i1.ɵeld(40, 0, null, null, 1, "figcaption", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Egill Antonsson dealing with the the dragon's breath"])), (_l()(), i1.ɵeld(42, 0, null, null, 40, "div", [], null, null, null, null, null)), (_l()(), i1.ɵeld(43, 0, null, null, 1, "h2", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["The beginning of my strength & hyperthropy journey"])), (_l()(), i1.ɵeld(45, 0, null, null, 1, "h3", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["The first workout"])), (_l()(), i1.ɵeld(47, 0, null, null, 11, "p", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" I've been lifting weights off and on since I was a 15 year old boy living in Reykjav\u00EDk, Iceland in 1997."])), (_l()(), i1.ɵeld(49, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" My first gym workout was with my friend Mummi who was training kick boxing and also hitting the gym to some extend at the time."])), (_l()(), i1.ɵeld(51, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" I'd like to think that he'd forgotten that this was my first workout ever and told me \"Today we are going to DESTROY the Biceps!\"."])), (_l()(), i1.ɵeld(53, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" I replied enthustically \"Sounds great!\", and then we went on taking many sets to failure with many forced reps."])), (_l()(), i1.ɵeld(55, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" Little did I know that this would leave me so sore that even the lightest bump in the arms would be agonisingly painful for a WEEK!"])), (_l()(), i1.ɵeld(57, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" This was a lesson learned for both me and Mummi in how not to begin your training.\n"])), (_l()(), i1.ɵeld(59, 0, null, null, 1, "h3", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["The first years"])), (_l()(), i1.ɵeld(61, 0, null, null, 4, "p", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" Although my first workout took weeks to recover from, I was eager to continue training for the next 3 to 4 years."])), (_l()(), i1.ɵeld(63, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" I frequently worked out in the gym called Gym 80 with my friend and lifting partner Kalli (Mummi was more into kick boxing)."])), (_l()(), i1.ɵeld(65, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i1.ɵeld(66, 0, null, null, 16, "p", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" Gym 80 was founded by "])), (_l()(), i1.ɵeld(68, 0, null, null, 1, "a", [["href", "https://en.wikipedia.org/wiki/J\u00F3n_P\u00E1ll_Sigmarsson"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["J\u00F3n P\u00E1ll Sigmarsson"])), (_l()(), i1.ɵted(-1, null, [" who was the first man in history to win the World Strongest Man four times."])), (_l()(), i1.ɵeld(71, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" He is a big inspiration to me as he was the first Icelandic athlete to be the best in the world in a sport, along being charismatic and entertaining."])), (_l()(), i1.ɵeld(73, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" My parents knew J\u00F3n's dad and they took a photo of J\u00F3n and me when I was around 6 years old.\nIn 1987 while making a strongman world record Deadlift of 523 kg, J\u00F3n shouted "])), (_l()(), i1.ɵeld(75, 0, null, null, 1, "a", [["href", "https://vimeo.com/57172348"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["\"There is no reason to be alive if you can't do deadlift!\""])), (_l()(), i1.ɵted(-1, null, [","])), (_l()(), i1.ɵeld(78, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["\nand as fate would have it he died in 1993, 32 years of age, of cardiac arrest due to an aortic rupture while deadlifting in his gym."])), (_l()(), i1.ɵeld(80, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["\nSo 5 years later me and Kalli were Deadlifting, Squatting and Bench Pressing at the very same spot where J\u00F3n P\u00E1ll Sigmarsson the Legend had died."])), (_l()(), i1.ɵeld(82, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i1.ɵeld(83, 0, null, null, 4, "div", [], null, null, null, null, null)), (_l()(), i1.ɵeld(84, 0, null, null, 3, "figure", [], null, null, null, null, null)), (_l()(), i1.ɵeld(85, 0, null, null, 0, "img", [["alt", "J\u00F3n P\u00E1ll Sigmarsson and Egill Antonsson"], ["class", "image"], ["src", "../assets/Egill_Antonsson_and_Jon_Pall.jpg"], ["title", "J\u00F3n P\u00E1ll Sigmarsson and Egill Antonsson"]], null, null, null, null, null)), (_l()(), i1.ɵeld(86, 0, null, null, 1, "figcaption", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["J\u00F3n P\u00E1ll Sigmarsson and Egill Antonsson around 1988. I'm wearing 80s top of the line clothing"]))], function (_ck, _v) { var _co = _v.component; var currVal_3 = _co.allCreaturesLifted; _ck(_v, 23, 0, currVal_3); }, function (_ck, _v) { var _co = _v.component; var currVal_0 = i1.ɵunv(_v, 6, 0, _ck(_v, 7, 0, i1.ɵnov(_v, 0), _co.firstDate, "d. MMMM yyyy")); var currVal_1 = i1.ɵunv(_v, 6, 1, _ck(_v, 8, 0, i1.ɵnov(_v, 0), _co.lastDate, "d. MMMM yyyy")); _ck(_v, 6, 0, currVal_0, currVal_1); var currVal_2 = i1.ɵunv(_v, 18, 0, _ck(_v, 19, 0, i1.ɵnov(_v, 1), _co.categoryKg.All, 0, "/", 1000)); _ck(_v, 18, 0, currVal_2); }); }
exports.View_LiftingComponent_0 = View_LiftingComponent_0;
function View_LiftingComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-lift", [], null, null, null, View_LiftingComponent_0, RenderType_LiftingComponent)), i1.ɵdid(1, 114688, null, 0, i4.LiftingComponent, [], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_LiftingComponent_Host_0 = View_LiftingComponent_Host_0;
var LiftingComponentNgFactory = i1.ɵccf("app-lift", i4.LiftingComponent, View_LiftingComponent_Host_0, {}, {}, []);
exports.LiftingComponentNgFactory = LiftingComponentNgFactory;


/***/ }),

/***/ "./src/app/lifting/lifting.component.ts":
/*!**********************************************!*\
  !*** ./src/app/lifting/lifting.component.ts ***!
  \**********************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var LiftingComponent = /** @class */ (function () {
    function LiftingComponent() {
    }
    LiftingComponent.prototype.ngOnInit = function () {
        var lifting_data = __webpack_require__(/*! ../../assets/lifting.json */ "./src/assets/lifting.json");
        this.categoryKg = lifting_data.category_kg;
        this.allCreaturesLifted = lifting_data.all_creatures_lifted;
        this.firstDate = new Date(lifting_data.first_date);
        this.lastDate = new Date(lifting_data.last_date);
    };
    return LiftingComponent;
}());
exports.LiftingComponent = LiftingComponent;


/***/ }),

/***/ "./src/app/music/music.component.css.shim.ngstyle.js":
/*!***********************************************************!*\
  !*** ./src/app/music/music.component.css.shim.ngstyle.js ***!
  \***********************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [".fadein[_ngcontent-%COMP%] {\r\n\t-webkit-animation: fadein 0.5s linear;\r\n\t        animation: fadein 0.5s linear;\r\n}\r\n\r\n@-webkit-keyframes fadein {\r\n\t0% {\r\n\t\topacity: 0;\r\n\t}\r\n\t100% {\r\n\t\topacity: 1;\r\n\t}\r\n}\r\n\r\n@keyframes fadein {\r\n\t0% {\r\n\t\topacity: 0;\r\n\t}\r\n\t100% {\r\n\t\topacity: 1;\r\n\t}\r\n}\r\n\r\n.fadeout[_ngcontent-%COMP%] {\r\n\t\r\n\t\r\n\tdisplay: none;\r\n}\r\n\r\n@-webkit-keyframes fadeout {\r\n\t0% {\r\n\t\topacity: 1;\r\n\t}\r\n\t100% {\r\n\t\topacity: 0;\r\n\t}\r\n}\r\n\r\n@keyframes fadeout {\r\n\t0% {\r\n\t\topacity: 1;\r\n\t}\r\n\t100% {\r\n\t\topacity: 0;\r\n\t}\r\n}\r\n\r\n.playerContainer[_ngcontent-%COMP%] {\r\n\tcursor: pointer;\r\n\tmargin: 0em 0.5em;\r\n\tborder: 0.5px solid #999;\r\n\tborder-radius: 1em;\r\n\tpadding: 0.6em 0.5em;\r\n}\r\n\r\n.playerText[_ngcontent-%COMP%] {\r\n\tfont-family: Arial, Helvetica, sans-serif;\r\n\tfont-weight: bold;\r\n}\r\n\r\n.playPauseContainer[_ngcontent-%COMP%] {\r\n\tfloat: left;\r\n\tpadding-left: 2.5%;\r\n\tpadding-top: 1px;\r\n\twidth: 8%;\r\n}\r\n\r\n.play[_ngcontent-%COMP%] {\r\n\t-webkit-clip-path: polygon(50% 0%, 0% 100%, 100% 100%);\r\n\t        clip-path: polygon(50% 0%, 0% 100%, 100% 100%);\r\n\tbackground: var(--activeColor);\r\n\twidth: 23px;\r\n\theight: 15px;\r\n\t-webkit-transform: translateX(-10%) translateY(10%) rotate(90deg);\r\n\t        transform: translateX(-10%) translateY(10%) rotate(90deg);\r\n\ttransition: all 0.2s;\r\n}\r\n\r\n.pause[_ngcontent-%COMP%] {\r\n\twidth: 7px;\r\n\theight: 18px;\r\n\tborder-right: 5px solid var(--pendingColor);\r\n\tborder-left: 5px solid var(--pendingColor);\r\n\ttransition: all 0.2s;\r\n}\r\n\r\n.byIconContainer[_ngcontent-%COMP%] {\r\n\tfloat: left;\r\n\twidth: 6%;\r\n}\r\n\r\n.byIcon[_ngcontent-%COMP%] {\r\n\tbackground: #969896;\r\n\twidth: 8px;\r\n\theight: 8px;\r\n\ttransition: all 0.2s;\r\n\tmargin: auto;\r\n}\r\n\r\n.animateClose[_ngcontent-%COMP%] {\r\n\t-webkit-transform: translateY(6px) rotate(0deg);\r\n\t        transform: translateY(6px) rotate(0deg);\r\n\ttransition: all 0.1s;\r\n}\r\n\r\n.animateOpen[_ngcontent-%COMP%] {\r\n\t\r\n\t-webkit-transform: translateY(5px) rotate(225deg);\r\n\t        transform: translateY(5px) rotate(225deg);\r\n\ttransition: all 0.4s ease-out;\r\n}\r\n\r\n.timer[_ngcontent-%COMP%] {\r\n\tfloat: right;\r\n\tpadding-right: 2.5%;\r\n\tpadding-top: 1.5px; \r\n}\r\n\r\nul[_ngcontent-%COMP%] {\r\n\tlist-style: none;\r\n\tcursor: pointer;\r\n}\r\n\r\n.allByContainer[_ngcontent-%COMP%] {\r\n\t margin-left: 1em;\r\n\t margin-top: 2em;\r\n\t margin-bottom: 2em;\r\n\t cursor: pointer;\r\n\t}\r\n\r\n.byContainer[_ngcontent-%COMP%] {\r\n\tmargin-top: 5px;\r\n\tmargin-bottom: 2px;\r\n}\r\n\r\n.trackContainer[_ngcontent-%COMP%] {\r\n\tmargin-left: 2em;\r\n\tline-height: 22px;\r\n}\r\n\r\n.track[_ngcontent-%COMP%] {\r\n\tfont-weight: bold;\r\n\tfont-family: Arial, Helvetica, sans-serif;\r\n\tpadding-top: 1.5px; \r\n}\r\n\r\n.buttonRow[_ngcontent-%COMP%] {\r\n\tmargin-left: 5%;\r\n}\r\n\r\n.button[_ngcontent-%COMP%] {\r\n\tbackground-color: #111;\r\n\tcolor: #ccc;\r\n\tfont-weight: bold;\r\n\tfont-family: Arial, Helvetica, sans-serif;\r\n\theight: 2em;\r\n\tmargin-right: 5%;\r\n\tfloat: left;\r\n\tborder: 1px solid #999;\r\n\tborder-radius: 0.5em;\r\n\tcursor: pointer;\r\n\ttransition-duration: 0.4s;\r\n}\r\n\r\n.button[_ngcontent-%COMP%]:hover {\r\n\tbackground-color: var(--pendingColor);\r\n\tborder-color: var(--pendingColor);\r\n\tcolor: #111;\r\n}\r\n\r\n.button[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] {\r\n\ttransition-duration: 1.0s;\r\n}\r\n\r\n.button[_ngcontent-%COMP%]:hover   a[_ngcontent-%COMP%] {\r\n\tbackground:transparent url('/assets/soundcloud_black.png') center top no-repeat;\r\n}\r\n\r\n.button[_ngcontent-%COMP%]:active {\r\n\tbackground-color: var(--activeColor);\r\n\tborder-color: var(--activeColor);\r\n}\r\n\r\n.button[_ngcontent-%COMP%]:focus {\r\n\toutline: 0;\r\n}\r\n\r\n.scLogo[_ngcontent-%COMP%] {\r\n\twidth: 104px;\r\n\theight: 16px;\r\n\tdisplay: block;\r\n\tbackground:transparent url('/assets/soundcloud.png') center top no-repeat;\r\n\t}\r\n\r\n.description[_ngcontent-%COMP%] {\r\n\tfloat: left;\r\n}"];
exports.styles = styles;


/***/ }),

/***/ "./src/app/music/music.component.ngfactory.js":
/*!****************************************************!*\
  !*** ./src/app/music/music.component.ngfactory.js ***!
  \****************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! ./music.component.css.shim.ngstyle */ "./src/app/music/music.component.css.shim.ngstyle.js");
var i1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i2 = __webpack_require__(/*! @angular/common */ "@angular/common");
var i3 = __webpack_require__(/*! ../pipes/minutesSeconds.pipe */ "./src/app/pipes/minutesSeconds.pipe.ts");
var i4 = __webpack_require__(/*! ./music.component */ "./src/app/music/music.component.ts");
var i5 = __webpack_require__(/*! ./soundcloud.service */ "./src/app/music/soundcloud.service.ts");
var styles_MusicComponent = [i0.styles];
var RenderType_MusicComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_MusicComponent, data: {} });
exports.RenderType_MusicComponent = RenderType_MusicComponent;
function View_MusicComponent_1(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 5, "span", [["class", "timer playerText"]], null, null, null, null, null)), i1.ɵdid(1, 278528, null, 0, i2.NgClass, [i1.IterableDiffers, i1.KeyValueDiffers, i1.ElementRef, i1.Renderer2], { klass: [0, "klass"], ngClass: [1, "ngClass"] }, null), i1.ɵpod(2, { fadein: 0 }), (_l()(), i1.ɵted(3, null, ["", " / ", ""])), i1.ɵppd(4, 1), i1.ɵppd(5, 1)], function (_ck, _v) { var _co = _v.component; var currVal_0 = "timer playerText"; var currVal_1 = _ck(_v, 2, 0, _co.isTrackReady); _ck(_v, 1, 0, currVal_0, currVal_1); }, function (_ck, _v) { var _co = _v.component; var currVal_2 = i1.ɵunv(_v, 3, 0, _ck(_v, 4, 0, i1.ɵnov(_v.parent, 0), _co.timeInSec)); var currVal_3 = i1.ɵunv(_v, 3, 1, _ck(_v, 5, 0, i1.ɵnov(_v.parent, 0), _co.selectedTrack.durationInSec)); _ck(_v, 3, 0, currVal_2, currVal_3); }); }
function View_MusicComponent_4(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 3, "div", [], null, [[null, "click"]], function (_v, en, $event) { var ad = true; var _co = _v.component; if (("click" === en)) {
        var pd_0 = (_co.onTrackClick(_v.context.$implicit) !== false);
        ad = (pd_0 && ad);
    } return ad; }, null, null)), i1.ɵdid(1, 278528, null, 0, i2.NgClass, [i1.IterableDiffers, i1.KeyValueDiffers, i1.ElementRef, i1.Renderer2], { ngClass: [0, "ngClass"] }, null), i1.ɵpod(2, { track: 0 }), (_l()(), i1.ɵted(3, null, [" ", " "]))], function (_ck, _v) { var _co = _v.component; var currVal_0 = _ck(_v, 2, 0, (_v.context.$implicit.id === _co.selectedTrack.id)); _ck(_v, 1, 0, currVal_0); }, function (_ck, _v) { var currVal_1 = _v.context.$implicit.name; _ck(_v, 3, 0, currVal_1); }); }
function View_MusicComponent_3(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 2, "div", [["class", "trackContainer fadein"]], null, null, null, null, null)), (_l()(), i1.ɵand(16777216, null, null, 1, null, View_MusicComponent_4)), i1.ɵdid(2, 278528, null, 0, i2.NgForOf, [i1.ViewContainerRef, i1.TemplateRef, i1.IterableDiffers], { ngForOf: [0, "ngForOf"] }, null)], function (_ck, _v) { var currVal_0 = _v.parent.context.$implicit.tracks; _ck(_v, 2, 0, currVal_0); }, null); }
function View_MusicComponent_2(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 9, "div", [], null, null, null, null, null)), (_l()(), i1.ɵeld(1, 0, null, null, 6, "div", [["class", "byContainer"]], null, [[null, "click"]], function (_v, en, $event) { var ad = true; var _co = _v.component; if (("click" === en)) {
        var pd_0 = (_co.onByClick(_v.context.index) !== false);
        ad = (pd_0 && ad);
    } return ad; }, null, null)), (_l()(), i1.ɵeld(2, 0, null, null, 3, "div", [["class", "byIconContainer"]], null, null, null, null, null)), (_l()(), i1.ɵeld(3, 0, null, null, 2, "div", [], null, null, null, null, null)), i1.ɵdid(4, 278528, null, 0, i2.NgClass, [i1.IterableDiffers, i1.KeyValueDiffers, i1.ElementRef, i1.Renderer2], { ngClass: [0, "ngClass"] }, null), i1.ɵpod(5, { byIcon: 0, animateClose: 1, animateOpen: 2 }), (_l()(), i1.ɵeld(6, 0, null, null, 1, "span", [], null, null, null, null, null)), (_l()(), i1.ɵted(7, null, ["", ""])), (_l()(), i1.ɵand(16777216, null, null, 1, null, View_MusicComponent_3)), i1.ɵdid(9, 16384, null, 0, i2.NgIf, [i1.ViewContainerRef, i1.TemplateRef], { ngIf: [0, "ngIf"] }, null)], function (_ck, _v) { var _co = _v.component; var currVal_0 = _ck(_v, 5, 0, true, (_co.openedUiByIndex != _v.context.index), (_co.openedUiByIndex === _v.context.index)); _ck(_v, 4, 0, currVal_0); var currVal_2 = (_co.openedUiByIndex === _v.context.index); _ck(_v, 9, 0, currVal_2); }, function (_ck, _v) { var currVal_1 = _v.context.$implicit.by; _ck(_v, 7, 0, currVal_1); }); }
function View_MusicComponent_6(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "button", [["class", "button"]], null, [[null, "click"]], function (_v, en, $event) { var ad = true; var _co = _v.component; if (("click" === en)) {
        var pd_0 = (_co.onBuyClick() !== false);
        ad = (pd_0 && ad);
    } return ad; }, null, null)), (_l()(), i1.ɵted(-1, null, ["Buy "]))], null, null); }
function View_MusicComponent_7(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 2, null, null, null, null, null, null, null)), (_l()(), i1.ɵted(1, null, [" ", ""])), (_l()(), i1.ɵeld(2, 0, null, null, 0, "br", [], null, null, null, null, null))], null, function (_ck, _v) { var currVal_0 = _v.context.$implicit; _ck(_v, 1, 0, currVal_0); }); }
function View_MusicComponent_5(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 10, "div", [], null, null, null, null, null)), i1.ɵdid(1, 278528, null, 0, i2.NgClass, [i1.IterableDiffers, i1.KeyValueDiffers, i1.ElementRef, i1.Renderer2], { ngClass: [0, "ngClass"] }, null), i1.ɵpod(2, { fadein: 0 }), (_l()(), i1.ɵeld(3, 0, null, null, 4, "div", [["class", "buttonRow"]], null, null, null, null, null)), (_l()(), i1.ɵeld(4, 0, null, null, 1, "button", [["class", "button"]], null, null, null, null, null)), (_l()(), i1.ɵeld(5, 0, null, null, 0, "a", [["class", "scLogo"], ["title", "These tracks on SoundCloud"]], [[8, "href", 4]], null, null, null, null)), (_l()(), i1.ɵand(16777216, null, null, 1, null, View_MusicComponent_6)), i1.ɵdid(7, 16384, null, 0, i2.NgIf, [i1.ViewContainerRef, i1.TemplateRef], { ngIf: [0, "ngIf"] }, null), (_l()(), i1.ɵeld(8, 0, null, null, 2, "p", [["class", "description"]], null, null, null, null, null)), (_l()(), i1.ɵand(16777216, null, null, 1, null, View_MusicComponent_7)), i1.ɵdid(10, 278528, null, 0, i2.NgForOf, [i1.ViewContainerRef, i1.TemplateRef, i1.IterableDiffers], { ngForOf: [0, "ngForOf"] }, null)], function (_ck, _v) { var _co = _v.component; var currVal_0 = _ck(_v, 2, 0, _co.isTrackReady); _ck(_v, 1, 0, currVal_0); var currVal_2 = _co.selectedTrack.purchaseUrl; _ck(_v, 7, 0, currVal_2); var currVal_3 = _co.getDescriptionLines(); _ck(_v, 10, 0, currVal_3); }, function (_ck, _v) { var _co = _v.component; var currVal_1 = i1.ɵinlineInterpolate(1, "", _co.selectedTrack.permalinkUrl, ""); _ck(_v, 5, 0, currVal_1); }); }
function View_MusicComponent_0(_l) { return i1.ɵvid(0, [i1.ɵpid(0, i3.MinutesSecondsPipe, []), (_l()(), i1.ɵeld(1, 0, null, null, 8, "div", [["class", "playerContainer"]], null, [[null, "click"]], function (_v, en, $event) { var ad = true; var _co = _v.component; if (("click" === en)) {
        var pd_0 = (_co.onPlayPause() !== false);
        ad = (pd_0 && ad);
    } return ad; }, null, null)), (_l()(), i1.ɵeld(2, 0, null, null, 3, "div", [["class", "playPauseContainer"]], null, null, null, null, null)), (_l()(), i1.ɵeld(3, 0, null, null, 2, "div", [], null, null, null, null, null)), i1.ɵdid(4, 278528, null, 0, i2.NgClass, [i1.IterableDiffers, i1.KeyValueDiffers, i1.ElementRef, i1.Renderer2], { ngClass: [0, "ngClass"] }, null), i1.ɵpod(5, { play: 0, pause: 1 }), (_l()(), i1.ɵeld(6, 0, null, null, 1, "span", [["class", "playerText"]], null, null, null, null, null)), (_l()(), i1.ɵted(7, null, ["", ""])), (_l()(), i1.ɵand(16777216, null, null, 1, null, View_MusicComponent_1)), i1.ɵdid(9, 16384, null, 0, i2.NgIf, [i1.ViewContainerRef, i1.TemplateRef], { ngIf: [0, "ngIf"] }, null), (_l()(), i1.ɵeld(10, 0, null, null, 2, "div", [["class", "allByContainer"]], null, null, null, null, null)), (_l()(), i1.ɵand(16777216, null, null, 1, null, View_MusicComponent_2)), i1.ɵdid(12, 278528, null, 0, i2.NgForOf, [i1.ViewContainerRef, i1.TemplateRef, i1.IterableDiffers], { ngForOf: [0, "ngForOf"] }, null), (_l()(), i1.ɵand(16777216, null, null, 1, null, View_MusicComponent_5)), i1.ɵdid(14, 16384, null, 0, i2.NgIf, [i1.ViewContainerRef, i1.TemplateRef], { ngIf: [0, "ngIf"] }, null)], function (_ck, _v) { var _co = _v.component; var currVal_0 = _ck(_v, 5, 0, !_co.isPlaying, _co.isPlaying); _ck(_v, 4, 0, currVal_0); var currVal_2 = _co.isTrackReady; _ck(_v, 9, 0, currVal_2); var currVal_3 = _co.byTracksArr; _ck(_v, 12, 0, currVal_3); var currVal_4 = _co.isTrackReady; _ck(_v, 14, 0, currVal_4); }, function (_ck, _v) { var _co = _v.component; var currVal_1 = _co.selectedTrack.name; _ck(_v, 7, 0, currVal_1); }); }
exports.View_MusicComponent_0 = View_MusicComponent_0;
function View_MusicComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-music", [], null, null, null, View_MusicComponent_0, RenderType_MusicComponent)), i1.ɵdid(1, 180224, null, 0, i4.MusicComponent, [i5.SoundCloudService], null, null)], null, null); }
exports.View_MusicComponent_Host_0 = View_MusicComponent_Host_0;
var MusicComponentNgFactory = i1.ɵccf("app-music", i4.MusicComponent, View_MusicComponent_Host_0, {}, {}, []);
exports.MusicComponentNgFactory = MusicComponentNgFactory;


/***/ }),

/***/ "./src/app/music/music.component.ts":
/*!******************************************!*\
  !*** ./src/app/music/music.component.ts ***!
  \******************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var soundcloud_service_1 = __webpack_require__(/*! ./soundcloud.service */ "./src/app/music/soundcloud.service.ts");
var MusicComponent = /** @class */ (function () {
    function MusicComponent(soundCloudService) {
        this.soundCloudService = soundCloudService;
        this.isInitalized = false;
        this.selectedTrack = { indexWithinBy: -1, name: 'select a track', id: -1, by: '', description: '', durationInSec: 0, hasPlayedOnce: false };
        this.selectedByIndex = -1;
        this.openedUiByIndex = -1;
        this.timeInSec = 0;
        this.byGogogic = 'Audio for Gogogic';
        this.byEgill = 'Egill Antonsson';
        this.byKuai = 'KUAI';
        this.byToo = 'Tribe of Oranges';
        this.bySeniors = 'Jónas & Egill seniors';
        this.SC = soundCloudService;
        this.SC.initialize({
            client_id: 'NZtb1cCBbHFHV67f1Fp9jkGKog0H4StA'
        });
        var byGogogicTracks = [
            { name: 'Vikings of Thule', id: 286944930 },
            { name: 'Iceland Socks Intro', id: 307751458 },
            { name: 'VoT (original mix)', id: 185133958 }
        ];
        var byEgillTracks = [
            { name: 'Fortíðin', id: 265756824 },
            { name: 'Toddler Tune', id: 244801989 },
            { name: 'Odd Times In Space', id: 273048355 },
            { name: 'LeCube', id: 212448413 }
        ];
        var byKuaiTracks = [
            { name: 'Pirringur', id: 493455450 },
            { name: 'Apollo', id: 493455435 },
            { name: 'Andsetinn', id: 493455411 },
            { name: 'Hamskipti', id: 493455396 },
            { name: 'Rover', id: 493455372 },
            { name: 'Andefni', id: 493455357 },
            { name: 'Agndofa', id: 493455342 },
            { name: 'Ofurte', id: 493455318 },
            { name: 'Lesblinda I', id: 493455303 },
            { name: 'Lesblinda II', id: 493455276 }
        ];
        var byTooTracks = [
            { name: 'Routine', id: 191481586 },
            { name: 'Introduction', id: 214031252 }
        ];
        var bySeniorsTracks = [
            { name: 'Rubber', id: 373876877 },
            { name: 'Mouse', id: 374218076 },
            { name: 'Gítarsólóin', id: 375296450 },
            { name: 'Tromm', id: 377705372 },
            { name: 'Pési', id: 375731609 }
        ];
        this.byTracksArr = [
            { by: this.byGogogic, tracks: byGogogicTracks },
            { by: this.byEgill, tracks: byEgillTracks },
            { by: this.byKuai, tracks: byKuaiTracks },
            { by: this.byToo, tracks: byTooTracks },
            { by: this.bySeniors, tracks: bySeniorsTracks }
        ];
        for (var i = 0; i < this.byTracksArr.length; i++) {
            for (var j = 0; j < this.byTracksArr[i].tracks.length; j++) {
                var track = this.byTracksArr[i].tracks[j];
                track.indexWithinBy = j;
                track.by = this.byTracksArr[i].by;
                track.hasPlayedOnce = false;
                track.description = '';
                track.durationInSec = 0;
            }
        }
    }
    MusicComponent.prototype.onByClick = function (byIndex) {
        if (this.openedUiByIndex === byIndex) {
            // deselect
            this.openedUiByIndex = -1;
        }
        else {
            this.openedUiByIndex = byIndex;
        }
    };
    MusicComponent.prototype.onTrackClick = function (track) {
        this.selectedByIndex = this.openedUiByIndex;
        this.playNewStream(track);
    };
    MusicComponent.prototype.onBuyClick = function () {
        window.open(this.selectedTrack.purchaseUrl);
    };
    MusicComponent.prototype.playNewStream = function (selectedTrack) {
        var _this = this;
        this.isInitalized = true;
        this.selectedTrack = selectedTrack;
        if (this.scPlayer != null) {
            this.scPlayer.kill();
        }
        this.isTrackReady = false;
        var trackUrl = '/tracks/' + this.selectedTrack.id.toString();
        this.SC.stream(trackUrl, function (player) {
            console.log('player');
            console.log(player);
            _this.scPlayer = player;
            player.on('time', function (millisec) {
                var sec = Math.floor(millisec / 1000);
                if (_this.timeInSec !== sec) {
                    _this.timeInSec = sec;
                }
            });
            player.on('finish', function () {
                var trackIndex = 0;
                if (_this.selectedTrack.indexWithinBy === _this.byTracksArr[_this.selectedByIndex].tracks.length - 1) {
                    if (_this.selectedByIndex === _this.byTracksArr.length - 1) {
                        _this.selectedByIndex = 0;
                    }
                    else {
                        _this.selectedByIndex++;
                    }
                }
                else {
                    trackIndex = _this.selectedTrack.indexWithinBy + 1;
                }
                _this.openedUiByIndex = _this.selectedByIndex;
                _this.playNewStream(_this.byTracksArr[_this.selectedByIndex].tracks[trackIndex]);
            });
            player.play();
            _this.isPlaying = true;
        });
        this.SC.get(trackUrl, function (track) {
            console.log('track');
            console.log(track);
            _this.isTrackReady = true;
            if (!_this.selectedTrack.hasPlayedOnce) {
                _this.selectedTrack.hasPlayedOnce = true;
                _this.selectedTrack.description = track.description;
                _this.selectedTrack.durationInSec = Math.floor(track.duration / 1000);
                _this.selectedTrack.purchaseUrl = track.purchase_url;
                _this.selectedTrack.permalinkUrl = track.permalink_url;
                _this.selectedTrack.liked = track.favoritings_count + 1;
            }
        });
    };
    MusicComponent.prototype.getDescriptionLines = function () {
        return this.selectedTrack.description.split('\n');
    };
    MusicComponent.prototype.onPlayPause = function () {
        if (this.selectedTrack.id === -1) {
            this.selectedByIndex = this.openedUiByIndex = 0;
            this.playNewStream(this.byTracksArr[this.selectedByIndex].tracks[0]);
            return;
        }
        if (this.scPlayer != null) {
            if (this.scPlayer.isPlaying()) {
                this.scPlayer.pause();
            }
            else {
                this.scPlayer.play();
            }
        }
        this.isPlaying = !this.isPlaying;
    };
    MusicComponent.prototype.ngOnDestroy = function () {
        if (this.scPlayer != null) {
            this.scPlayer.kill();
        }
    };
    return MusicComponent;
}());
exports.MusicComponent = MusicComponent;


/***/ }),

/***/ "./src/app/music/soundcloud.service.ts":
/*!*********************************************!*\
  !*** ./src/app/music/soundcloud.service.ts ***!
  \*********************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! @angular/core */ "@angular/core");
var SoundCloudService = /** @class */ (function () {
    function SoundCloudService() {
        this.soundcloud = __webpack_require__(/*! soundcloud */ "soundcloud");
    }
    SoundCloudService.prototype.initialize = function (obj) {
        this.soundcloud.initialize(obj);
    };
    SoundCloudService.prototype.stream = function (trackUrl, callback) {
        this.soundcloud.stream(trackUrl).then(function (player) {
            callback(player);
        });
    };
    SoundCloudService.prototype.get = function (trackUrl, callback) {
        this.soundcloud.get(trackUrl).then(function (track) {
            callback(track);
        });
    };
    SoundCloudService.ngInjectableDef = i0.defineInjectable({ factory: function SoundCloudService_Factory() { return new SoundCloudService(); }, token: SoundCloudService, providedIn: "root" });
    return SoundCloudService;
}());
exports.SoundCloudService = SoundCloudService;


/***/ }),

/***/ "./src/app/pagenotfound.component.ngfactory.js":
/*!*****************************************************!*\
  !*** ./src/app/pagenotfound.component.ngfactory.js ***!
  \*****************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i1 = __webpack_require__(/*! ./pagenotfound.component */ "./src/app/pagenotfound.component.ts");
var styles_PageNotFoundComponent = [];
var RenderType_PageNotFoundComponent = i0.ɵcrt({ encapsulation: 2, styles: styles_PageNotFoundComponent, data: {} });
exports.RenderType_PageNotFoundComponent = RenderType_PageNotFoundComponent;
function View_PageNotFoundComponent_0(_l) { return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, 0, null, null, 1, "h2", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, ["Page not found for this url"]))], null, null); }
exports.View_PageNotFoundComponent_0 = View_PageNotFoundComponent_0;
function View_PageNotFoundComponent_Host_0(_l) { return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, 0, null, null, 1, "app-pagenotfound", [], null, null, null, View_PageNotFoundComponent_0, RenderType_PageNotFoundComponent)), i0.ɵdid(1, 49152, null, 0, i1.PageNotFoundComponent, [], null, null)], null, null); }
exports.View_PageNotFoundComponent_Host_0 = View_PageNotFoundComponent_Host_0;
var PageNotFoundComponentNgFactory = i0.ɵccf("app-pagenotfound", i1.PageNotFoundComponent, View_PageNotFoundComponent_Host_0, {}, {}, []);
exports.PageNotFoundComponentNgFactory = PageNotFoundComponentNgFactory;


/***/ }),

/***/ "./src/app/pagenotfound.component.ts":
/*!*******************************************!*\
  !*** ./src/app/pagenotfound.component.ts ***!
  \*******************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var PageNotFoundComponent = /** @class */ (function () {
    function PageNotFoundComponent() {
    }
    return PageNotFoundComponent;
}());
exports.PageNotFoundComponent = PageNotFoundComponent;


/***/ }),

/***/ "./src/app/pipes/minutesSeconds.pipe.ts":
/*!**********************************************!*\
  !*** ./src/app/pipes/minutesSeconds.pipe.ts ***!
  \**********************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var MinutesSecondsPipe = /** @class */ (function () {
    function MinutesSecondsPipe() {
    }
    MinutesSecondsPipe.prototype.transform = function (seconds) {
        var min = Math.floor(seconds / 60).toString();
        var remainingSec = (seconds % 60).toString();
        var secondsPadding = (seconds % 60 < 10) ? ':0' : ':';
        return min + secondsPadding + remainingSec;
    };
    return MinutesSecondsPipe;
}());
exports.MinutesSecondsPipe = MinutesSecondsPipe;


/***/ }),

/***/ "./src/app/pipes/mynumber.pipe.ts":
/*!****************************************!*\
  !*** ./src/app/pipes/mynumber.pipe.ts ***!
  \****************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var MyNumberPipe = /** @class */ (function () {
    function MyNumberPipe() {
    }
    MyNumberPipe.prototype.transform = function (value, decimalDigits, conversionSign, conversionAmount) {
        if (decimalDigits === void 0) { decimalDigits = 0; }
        if (conversionSign === void 0) { conversionSign = '*'; }
        if (conversionAmount === void 0) { conversionAmount = 1; }
        var conversedValue;
        switch (conversionSign) {
            case '/':
                conversedValue = value / conversionAmount;
                break;
            case '*':
                conversedValue = value * conversionAmount;
                break;
            default:
                throw new RangeError('parameter "conversionSign" can only have value "/" or "*"');
        }
        var originalString = conversedValue.toFixed(decimalDigits);
        var formattedStringList = [];
        var index = originalString.includes('.') ? originalString.indexOf('.') : originalString.length;
        var formatLength = 3;
        if (index < formatLength) {
            return originalString;
        }
        var firstLoop = true;
        while (index > 0) {
            index = index - 3;
            if (index <= 0) {
                formattedStringList.unshift(originalString.substr(0, formatLength + index));
            }
            else {
                if (firstLoop) {
                    formattedStringList.unshift(originalString.substr(index));
                    firstLoop = false;
                }
                else {
                    formattedStringList.unshift(originalString.substr(index, formatLength));
                }
            }
        }
        return formattedStringList.join('\'');
    };
    return MyNumberPipe;
}());
exports.MyNumberPipe = MyNumberPipe;


/***/ }),

/***/ "./src/app/programming/programming.component.ngfactory.js":
/*!****************************************************************!*\
  !*** ./src/app/programming/programming.component.ngfactory.js ***!
  \****************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i1 = __webpack_require__(/*! ./programming.component */ "./src/app/programming/programming.component.ts");
var styles_ProgrammingComponent = [];
var RenderType_ProgrammingComponent = i0.ɵcrt({ encapsulation: 2, styles: styles_ProgrammingComponent, data: {} });
exports.RenderType_ProgrammingComponent = RenderType_ProgrammingComponent;
function View_ProgrammingComponent_0(_l) { return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, 0, null, null, 1, "h2", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, ["Building with the bleeps and bloops and the 1s and 0s"])), (_l()(), i0.ɵeld(2, 0, null, null, 11, "p", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, [" My code repositories are on "])), (_l()(), i0.ɵeld(4, 0, null, null, 1, "a", [["href", "https://github.com/EgillAntonsson"]], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, ["GitHub"])), (_l()(), i0.ɵted(-1, null, [","])), (_l()(), i0.ɵeld(7, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, [" and so are my "])), (_l()(), i0.ɵeld(9, 0, null, null, 1, "a", [["href", "https://gist.github.com/EgillAntonsson"]], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, ["code snippets"])), (_l()(), i0.ɵted(-1, null, ["."])), (_l()(), i0.ɵeld(12, 0, null, null, 0, "br", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, [" The main repositories are:\n"])), (_l()(), i0.ɵeld(14, 0, null, null, 2, "h3", [], null, null, null, null, null)), (_l()(), i0.ɵeld(15, 0, null, null, 1, "a", [["href", "https://github.com/EgillAntonsson/EgillAntonsson-website"]], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, ["Egill Antonsson website - Development"])), (_l()(), i0.ɵeld(17, 0, null, null, 1, "p", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, [" The development project of this website (yes the one you're reading right now!)\n"])), (_l()(), i0.ɵeld(19, 0, null, null, 2, "h3", [], null, null, null, null, null)), (_l()(), i0.ɵeld(20, 0, null, null, 1, "a", [["href", "https://github.com/EgillAntonsson/EgillAntonsson.github.io"]], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, ["Egill Antonsson website - Deploy"])), (_l()(), i0.ɵeld(22, 0, null, null, 1, "p", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, [" The code repository where the production ready files of this website (yes the one you're reading right now!) are pushed to and then deployed.\n"]))], null, null); }
exports.View_ProgrammingComponent_0 = View_ProgrammingComponent_0;
function View_ProgrammingComponent_Host_0(_l) { return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, 0, null, null, 1, "app-programming", [], null, null, null, View_ProgrammingComponent_0, RenderType_ProgrammingComponent)), i0.ɵdid(1, 49152, null, 0, i1.ProgrammingComponent, [], null, null)], null, null); }
exports.View_ProgrammingComponent_Host_0 = View_ProgrammingComponent_Host_0;
var ProgrammingComponentNgFactory = i0.ɵccf("app-programming", i1.ProgrammingComponent, View_ProgrammingComponent_Host_0, {}, {}, []);
exports.ProgrammingComponentNgFactory = ProgrammingComponentNgFactory;


/***/ }),

/***/ "./src/app/programming/programming.component.ts":
/*!******************************************************!*\
  !*** ./src/app/programming/programming.component.ts ***!
  \******************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var ProgrammingComponent = /** @class */ (function () {
    function ProgrammingComponent() {
    }
    return ProgrammingComponent;
}());
exports.ProgrammingComponent = ProgrammingComponent;


/***/ }),

/***/ "./src/assets/lifting.json":
/*!*********************************!*\
  !*** ./src/assets/lifting.json ***!
  \*********************************/
/*! exports provided: first_date, last_date, category_kg, all_creatures_lifted, default */
/***/ (function(module) {

module.exports = {"first_date":"2016-07-15","last_date":"2018-08-09","category_kg":{"Shoulders":164443.5,"Back":515762.7,"Abs":149099.8,"All":2191011.8,"Triceps":106082.3,"Chest":347622.5,"Legs":551060.5,"Calves":272030,"Biceps":82465.5},"all_creatures_lifted":[{"total_kg":1741800,"count":3,"creature":{"name":"Gold dragon","kg":580600,"url":"http://forgottenrealms.wikia.com/wiki/Gold_dragon"}},{"total_kg":435450,"count":6,"creature":{"name":"Bronze dragon","kg":72575,"url":"http://forgottenrealms.wikia.com/wiki/Bronze_dragon"}},{"total_kg":11380,"count":1,"creature":{"name":"Baird's beaked whale","kg":11380,"url":"http://us.whales.org/species-guide/bairds-beaked-whale"}},{"total_kg":2200,"count":1,"creature":{"name":"Short-finned pilot whale","kg":2200,"url":"http://uk.whales.org/species-guide/short-finned-pilot-whale"}},{"total_kg":180,"count":1,"creature":{"name":"Wild boar","kg":180,"url":"https://en.wikipedia.org/wiki/Wild_boar"}},{"total_kg":1,"count":1,"creature":{"name":"Guinea pig","kg":1,"url":"https://en.wikipedia.org/wiki/Guinea_pig"}},{"total_kg":0.5,"count":1,"creature":{"name":"African hedgehog","kg":0.5,"url":"https://www.awf.org/wildlife-conservation/hedgehog"}}]};

/***/ }),

/***/ "./src/main.server.ts":
/*!****************************!*\
  !*** ./src/main.server.ts ***!
  \****************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var app_server_module_ngfactory_1 = __webpack_require__(/*! ./app/app.server.module.ngfactory */ "./src/app/app.server.module.ngfactory.js");
exports.AppServerModuleNgFactory = app_server_module_ngfactory_1.AppServerModuleNgFactory;
var app_server_module_1 = __webpack_require__(/*! ./app/app.server.module */ "./src/app/app.server.module.ts");
exports.AppServerModule = app_server_module_1.AppServerModule;
exports.LAZY_MODULE_MAP = {};


/***/ }),

/***/ 0:
/*!**********************************!*\
  !*** multi ./src/main.server.ts ***!
  \**********************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

module.exports = __webpack_require__(/*! C:\Users\ea\code\egillantonsson-website\src\main.server.ts */"./src/main.server.ts");


/***/ }),

/***/ "@angular/animations":
/*!**************************************!*\
  !*** external "@angular/animations" ***!
  \**************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/animations");

/***/ }),

/***/ "@angular/animations/browser":
/*!**********************************************!*\
  !*** external "@angular/animations/browser" ***!
  \**********************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/animations/browser");

/***/ }),

/***/ "@angular/common":
/*!**********************************!*\
  !*** external "@angular/common" ***!
  \**********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/common");

/***/ }),

/***/ "@angular/common/http":
/*!***************************************!*\
  !*** external "@angular/common/http" ***!
  \***************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/common/http");

/***/ }),

/***/ "@angular/core":
/*!********************************!*\
  !*** external "@angular/core" ***!
  \********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/core");

/***/ }),

/***/ "@angular/http":
/*!********************************!*\
  !*** external "@angular/http" ***!
  \********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/http");

/***/ }),

/***/ "@angular/platform-browser":
/*!********************************************!*\
  !*** external "@angular/platform-browser" ***!
  \********************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/platform-browser");

/***/ }),

/***/ "@angular/platform-browser/animations":
/*!*******************************************************!*\
  !*** external "@angular/platform-browser/animations" ***!
  \*******************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/platform-browser/animations");

/***/ }),

/***/ "@angular/platform-server":
/*!*******************************************!*\
  !*** external "@angular/platform-server" ***!
  \*******************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/platform-server");

/***/ }),

/***/ "@angular/router":
/*!**********************************!*\
  !*** external "@angular/router" ***!
  \**********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/router");

/***/ }),

/***/ "@nguniversal/module-map-ngfactory-loader":
/*!***********************************************************!*\
  !*** external "@nguniversal/module-map-ngfactory-loader" ***!
  \***********************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@nguniversal/module-map-ngfactory-loader");

/***/ }),

/***/ "soundcloud":
/*!*****************************!*\
  !*** external "soundcloud" ***!
  \*****************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("soundcloud");

/***/ })

/******/ })));
//# sourceMappingURL=main.js.map